/* Generated By:JavaCC: Do not edit this line. MyPythonGrammarVisitor.java Version 5.0 */
package com.python.pv;

public interface MyPythonGrammarVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=40fd164701b89ff37b5e464c1da0e475 (do not edit this line) */
