/* Generated By:JJTree&JavaCC: Do not edit this line. MyPythonGrammarConstants.java */
package com.python.pv;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyPythonGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQU = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int LP = 9;
  /** RegularExpression Id. */
  int RP = 10;
  /** RegularExpression Id. */
  int EQ = 11;
  /** RegularExpression Id. */
  int NOTEQ = 12;
  /** RegularExpression Id. */
  int LT = 13;
  /** RegularExpression Id. */
  int SMALLEQ = 14;
  /** RegularExpression Id. */
  int NEQ = 15;
  /** RegularExpression Id. */
  int OR = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int ISTO = 18;
  /** RegularExpression Id. */
  int IMPLY = 19;
  /** RegularExpression Id. */
  int BIGEQ = 20;
  /** RegularExpression Id. */
  int POINT = 21;
  /** RegularExpression Id. */
  int YINHAO = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int FENHAO = 24;
  /** RegularExpression Id. */
  int LB = 25;
  /** RegularExpression Id. */
  int RB = 26;
  /** RegularExpression Id. */
  int OBRACE = 27;
  /** RegularExpression Id. */
  int CBARCE = 28;
  /** RegularExpression Id. */
  int IF = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int IMPORT = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int CLIENT = 34;
  /** RegularExpression Id. */
  int SERVER = 35;
  /** RegularExpression Id. */
  int ident = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"==\"",
    "\"!=\"",
    "\"< \"",
    "\"<=\"",
    "\"<>\"",
    "\"||\"",
    "\"&&\"",
    "\"==>\"",
    "\"->\"",
    "\">=\"",
    "\".\"",
    "\"^\"",
    "\",\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\"import\"",
    "\"while\"",
    "\"true\"",
    "\"Client\"",
    "\"Server\"",
    "<ident>",
    "<LETTER>",
    "<DIGIT>",
  };

}
