/* Generated By:JavaCC: Do not edit this line. MyPythonGrammarTreeConstants.java Version 5.0 */
package com.python.pv;

public interface MyPythonGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTHEADPARA = 1;
  public int JJTFIRSTPARA = 2;
  public int JJTSECONDPARA = 3;
  public int JJTTHIRDPARA = 4;
  public int JJTFORTHPARA = 5;
  public int JJTCOMMASTATE = 6;
  public int JJTGETSOCKETHOST = 7;
  public int JJTCOMMAFUN = 8;
  public int JJTSOCKETBIND = 9;
  public int JJTOUTBAND = 10;
  public int JJTFIRSTASSIGN = 11;
  public int JJTCONDITION = 12;
  public int JJTIDENTIFIER = 13;
  public int JJTPOINTMETHOD = 14;
  public int JJTINTEGER = 15;
  public int JJTEQU = 16;
  public int JJTEQSTATE = 17;
  public int JJTBIGER = 18;
  public int JJTSMALLER = 19;
  public int JJTNOTEQ = 20;
  public int JJTFENHAO = 21;
  public int JJTELSESTATE = 22;
  public int JJTIF = 23;
  public int JJTIMPORTPACKGE = 24;
  public int JJTWHILETRUE = 25;
  public int JJTSOCKETTRUE = 26;
  public int JJTSOCKETLP = 27;
  public int JJTSOCKETRP = 28;
  public int JJTSOCKETLETTER = 29;
  public int JJTSOCKETCOMMA = 30;
  public int JJTCLIENTIMPORT = 31;
  public int JJTSERVERIMPORT = 32;


  public String[] jjtNodeName = {
    "Start",
    "HeadPara",
    "FirstPara",
    "SecondPara",
    "ThirdPara",
    "ForthPara",
    "commastate",
    "getsockethost",
    "commafun",
    "socketbind",
    "outband",
    "Firstassign",
    "condition",
    "Identifier",
    "pointmethod",
    "Integer",
    "Equ",
    "EQstate",
    "biger",
    "smaller",
    "noteq",
    "fenhao",
    "elsestate",
    "If",
    "importpackge",
    "whiletrue",
    "sockettrue",
    "socketlp",
    "socketrp",
    "socketletter",
    "socketcomma",
    "clientimport",
    "serverimport",
  };
}
/* JavaCC - OriginalChecksum=e9913beb42c02f7068ba2fe45b83eab4 (do not edit this line) */
